# Generated by Django 4.2.4 on 2023-08-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('upfront_comm_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trail_comm_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'Lender',
            },
        ),
    ]
